apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
  labels:
    app: hello-service
  namespace: nju18
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: hello-service
    spec:
      containers:
        - name: hello-service
          image: harbor.edu.cn/nju18/hello-service:{VERSION}
          imagePullPolicy: IfNotPresent
#          resources:
#            requests:
#              cpu: 1
#              memory: 512Mi
#            limits:
#              cpu: 1
#              memory: 512Mi
      imagePullSecrets:
        - name: harbor