apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    app: hello-service