server:
  port: 8090
spring:
  application:
    name: hello-service
  cache:
    type: redis
    redis:
      cache-null-values: true
  redis:
    redisson:
      file: classpath:redisson-dev.yaml



